In [ ]:
#Importing python Libraries required for data analysis and visualization

import pandas as pd   #(Pandas for handling data)
import numpy as np    #(Numpy for numerical operations)
import matplotlib.pyplot as plt   #(Matplotlib for visulization)

In [ ]:
# Loading the dataset into dataframe for analysis

df = pd.read_csv("cookie_cats.csv")    #(Imported csv file)

In [ ]:
#taking a quick look at our dataset

df.head()    #(Displays the first five rows of dataset)

#displays the types of values
#We can see column names

   userid  version  sum_gamerounds  retention_1  retention_7
0     116  gate_30               3        False        False
1     337  gate_30              38         True        False
2     377  gate_40             165         True        False
3     483  gate_40               1        False        False
4     488  gate_40             179         True         True

In [ ]:
#Checking the structure of dataset

df.info()    #(I used this to check wether dataset is clean and have no missing values)

#shows numbers of rows and columns
#data types of each column

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90189 entries, 0 to 90188
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   userid          90189 non-null  int64
 1   version         90189 non-null  object
 2   sum_gamerounds  90189 non-null  int64
 3   retention_1     90189 non-null  bool
 4   retention_7     90189 non-null  bool
dtypes: bool(2), int64(2), object(1)
memory usage: 2.2+ MB

In [ ]:
#This will display statistical summary of the dataset(numerical columns)

df.describe()    #(helps to understand the data distribution)

#With help of this we have MEAN , Maximum & Minimum values , Standard deviation

             userid  sum_gamerounds
count  9.018900e+04    90189.000000
mean   4.998412e+06       51.872457
std    2.883286e+06      195.050858
min    1.160000e+02        0.000000
25%    2.512230e+06        5.000000
50%    4.995815e+06       16.000000
75%    7.496452e+06       51.000000
max    9.999861e+06    49854.000000

In [ ]:
#Checking the distribution users in groups

df["version"].value_counts()    #(To check wether both groups are balanced)

#This will show number of users in gate_30
#This will show number of users in gate_40 (Test group)

version
gate_40    45489
gate_30    44700
Name: count, dtype: int64

In [ ]:
#I am calculating the average retention rate of each group

df.groupby("version")["retention_1"].mean()       #(Comparing A/B test results)

#This will tell which group has higher retention

version
gate_30    0.448188
gate_40    0.442283
Name: retention_1, dtype: float64

NEXT STEP : Hypothesis Testing(A/B)

- Objective of this is to determine whether changing the game level gate from 30 to 40 has a statistical impact on players retention. -

- Starting with setting up our hypotheses:

> NUll Hypothesis: There is no difference in retention between two groups.

> Alternative hypothesis : There is